-- AlterTable
ALTER TABLE "Expense" ALTER COLUMN "budget" SET DATA TYPE BIGINT,
ALTER COLUMN "realized" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "Financing" ALTER COLUMN "amount" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "Revenue" ALTER COLUMN "budget" SET DATA TYPE BIGINT,
ALTER COLUMN "realized" SET DATA TYPE BIGINT;
