-- AlterTable
ALTER TABLE "Expense" ALTER COLUMN "budget" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "realized" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "Financing" ALTER COLUMN "amount" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "Revenue" ALTER COLUMN "budget" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "realized" SET DATA TYPE DECIMAL(65,30);
